apiVersion: v1
kind: Pod

metadata:
  name: secret-demo
  namespace: k8s-demo

spec:

  containers:

    - name: nginx
      image: nginx:1.27

      env:

        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: username

        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
